{{- if .Values.config.secrets }}
{{- range $secretName, $secretData := .Values.config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" $ }}-{{ $secretName }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" $ | nindent 4 }}
    app.kubernetes.io/component: secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" $ | nindent 4 }}
type: {{ $secretData.type | default "Opaque" }}
data:
  {{- range $key, $value := $secretData.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}

# Database credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-database-credentials
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.databases.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.databases.postgresql.auth.password | b64enc }}
  POSTGRES_URL: {{ include "ventaro-ai.postgresqlUrl" . | b64enc }}
  {{- end }}
  {{- if .Values.databases.mongodb.enabled }}
  MONGODB_PASSWORD: {{ .Values.databases.mongodb.auth.password | b64enc }}
  MONGODB_ROOT_PASSWORD: {{ .Values.databases.mongodb.auth.rootPassword | b64enc }}
  MONGODB_URL: {{ include "ventaro-ai.mongodbUrl" . | b64enc }}
  {{- end }}
  {{- if .Values.databases.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.databases.redis.auth.password | b64enc }}
  REDIS_URL: {{ include "ventaro-ai.redisUrl" . | b64enc }}
  {{- end }}
  {{- if .Values.databases.influxdb.enabled }}
  INFLUXDB_PASSWORD: {{ .Values.databases.influxdb.auth.admin.password | b64enc }}
  INFLUXDB_TOKEN: {{ .Values.databases.influxdb.auth.admin.token | b64enc }}
  INFLUXDB_URL: {{ include "ventaro-ai.influxdbUrl" . | b64enc }}
  {{- end }}

---
# API Keys and external service credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-api-keys
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  # AI/ML API Keys
  {{- if .Values.config.apiKeys.openai }}
  OPENAI_API_KEY: {{ .Values.config.apiKeys.openai | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.anthropic }}
  ANTHROPIC_API_KEY: {{ .Values.config.apiKeys.anthropic | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.huggingface }}
  HUGGINGFACE_API_KEY: {{ .Values.config.apiKeys.huggingface | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.cohere }}
  COHERE_API_KEY: {{ .Values.config.apiKeys.cohere | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.replicate }}
  REPLICATE_API_TOKEN: {{ .Values.config.apiKeys.replicate | b64enc }}
  {{- end }}
  
  # Cloud Provider Keys
  {{- if .Values.config.apiKeys.aws.accessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.config.apiKeys.aws.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.apiKeys.aws.secretKey | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.gcp.serviceAccount }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.config.apiKeys.gcp.serviceAccount | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.azure.clientSecret }}
  AZURE_CLIENT_ID: {{ .Values.config.apiKeys.azure.clientId | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.config.apiKeys.azure.clientSecret | b64enc }}
  AZURE_TENANT_ID: {{ .Values.config.apiKeys.azure.tenantId | b64enc }}
  {{- end }}
  
  # Communication Services
  {{- if .Values.config.apiKeys.twilio.authToken }}
  TWILIO_ACCOUNT_SID: {{ .Values.config.apiKeys.twilio.accountSid | b64enc }}
  TWILIO_AUTH_TOKEN: {{ .Values.config.apiKeys.twilio.authToken | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.sendgrid }}
  SENDGRID_API_KEY: {{ .Values.config.apiKeys.sendgrid | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.slack }}
  SLACK_BOT_TOKEN: {{ .Values.config.apiKeys.slack | b64enc }}
  {{- end }}
  
  # Payment Services
  {{- if .Values.config.apiKeys.stripe.secretKey }}
  STRIPE_SECRET_KEY: {{ .Values.config.apiKeys.stripe.secretKey | b64enc }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.config.apiKeys.stripe.publishableKey | b64enc }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.config.apiKeys.stripe.webhookSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.paypal.clientSecret }}
  PAYPAL_CLIENT_ID: {{ .Values.config.apiKeys.paypal.clientId | b64enc }}
  PAYPAL_CLIENT_SECRET: {{ .Values.config.apiKeys.paypal.clientSecret | b64enc }}
  {{- end }}
  
  # Analytics and Monitoring
  {{- if .Values.config.apiKeys.googleAnalytics }}
  GOOGLE_ANALYTICS_ID: {{ .Values.config.apiKeys.googleAnalytics | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.mixpanel }}
  MIXPANEL_TOKEN: {{ .Values.config.apiKeys.mixpanel | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.datadog }}
  DATADOG_API_KEY: {{ .Values.config.apiKeys.datadog | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.newRelic }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.config.apiKeys.newRelic | b64enc }}
  {{- end }}
  
  # Content and Media
  {{- if .Values.config.apiKeys.cloudinary.apiSecret }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.config.apiKeys.cloudinary.cloudName | b64enc }}
  CLOUDINARY_API_KEY: {{ .Values.config.apiKeys.cloudinary.apiKey | b64enc }}
  CLOUDINARY_API_SECRET: {{ .Values.config.apiKeys.cloudinary.apiSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.unsplash }}
  UNSPLASH_ACCESS_KEY: {{ .Values.config.apiKeys.unsplash | b64enc }}
  {{- end }}
  
  # Blockchain and Crypto
  {{- if .Values.config.apiKeys.alchemy }}
  ALCHEMY_API_KEY: {{ .Values.config.apiKeys.alchemy | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.infura.projectSecret }}
  INFURA_PROJECT_ID: {{ .Values.config.apiKeys.infura.projectId | b64enc }}
  INFURA_PROJECT_SECRET: {{ .Values.config.apiKeys.infura.projectSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.apiKeys.coinbase }}
  COINBASE_API_KEY: {{ .Values.config.apiKeys.coinbase | b64enc }}
  {{- end }}

---
# JWT and Authentication secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-auth-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.config.auth.jwtSecret | b64enc }}
  JWT_REFRESH_SECRET: {{ .Values.config.auth.jwtRefreshSecret | b64enc }}
  SESSION_SECRET: {{ .Values.config.auth.sessionSecret | b64enc }}
  ENCRYPTION_KEY: {{ .Values.config.auth.encryptionKey | b64enc }}
  
  # OAuth credentials
  {{- if .Values.config.auth.oauth.google.clientSecret }}
  GOOGLE_CLIENT_ID: {{ .Values.config.auth.oauth.google.clientId | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.config.auth.oauth.google.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.oauth.github.clientSecret }}
  GITHUB_CLIENT_ID: {{ .Values.config.auth.oauth.github.clientId | b64enc }}
  GITHUB_CLIENT_SECRET: {{ .Values.config.auth.oauth.github.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.oauth.microsoft.clientSecret }}
  MICROSOFT_CLIENT_ID: {{ .Values.config.auth.oauth.microsoft.clientId | b64enc }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.config.auth.oauth.microsoft.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.config.auth.oauth.discord.clientSecret }}
  DISCORD_CLIENT_ID: {{ .Values.config.auth.oauth.discord.clientId | b64enc }}
  DISCORD_CLIENT_SECRET: {{ .Values.config.auth.oauth.discord.clientSecret | b64enc }}
  {{- end }}

---
# TLS certificates
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-tls-cert
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    cert-manager.io/issuer: {{ .Values.ingress.tls.issuer | default "letsencrypt-prod" }}
type: kubernetes.io/tls
data:
  {{- if .Values.ingress.tls.certificate }}
  tls.crt: {{ .Values.ingress.tls.certificate | b64enc }}
  {{- end }}
  {{- if .Values.ingress.tls.privateKey }}
  tls.key: {{ .Values.ingress.tls.privateKey | b64enc }}
  {{- end }}
---
{{- end }}

# Docker registry credentials
{{- if .Values.global.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-registry-credentials
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecrets | toJson | b64enc }}
---
{{- end }}

# Webhook secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-webhook-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  WEBHOOK_SECRET: {{ .Values.config.webhooks.secret | default (randAlphaNum 32) | b64enc }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.config.webhooks.github | default (randAlphaNum 32) | b64enc }}
  GITLAB_WEBHOOK_SECRET: {{ .Values.config.webhooks.gitlab | default (randAlphaNum 32) | b64enc }}
  SLACK_WEBHOOK_URL: {{ .Values.config.webhooks.slack | default "" | b64enc }}
  DISCORD_WEBHOOK_URL: {{ .Values.config.webhooks.discord | default "" | b64enc }}

---
# Backup and disaster recovery secrets
{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-backup-credentials
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backup.s3.accessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.backup.s3.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.s3.secretKey | b64enc }}
  {{- end }}
  {{- if .Values.backup.gcs.serviceAccount }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.backup.gcs.serviceAccount | b64enc }}
  {{- end }}
  {{- if .Values.backup.azure.accountKey }}
  AZURE_STORAGE_ACCOUNT: {{ .Values.backup.azure.accountName | b64enc }}
  AZURE_STORAGE_KEY: {{ .Values.backup.azure.accountKey | b64enc }}
  {{- end }}
---
{{- end }}

# IoT and Edge computing secrets
{{- if .Values.features.iot.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-iot-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: iot-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  MQTT_USERNAME: {{ .Values.config.iot.mqtt.username | default "ventaro" | b64enc }}
  MQTT_PASSWORD: {{ .Values.config.iot.mqtt.password | default (randAlphaNum 32) | b64enc }}
  IOT_DEVICE_KEY: {{ .Values.config.iot.deviceKey | default (randAlphaNum 64) | b64enc }}
  IOT_CA_CERT: {{ .Values.config.iot.caCert | default "" | b64enc }}
  IOT_CLIENT_CERT: {{ .Values.config.iot.clientCert | default "" | b64enc }}
  IOT_CLIENT_KEY: {{ .Values.config.iot.clientKey | default "" | b64enc }}
---
{{- end }}

# Blockchain and Web3 secrets
{{- if .Values.features.blockchain.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-blockchain-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: blockchain-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  PRIVATE_KEY: {{ .Values.config.blockchain.privateKey | default "" | b64enc }}
  MNEMONIC: {{ .Values.config.blockchain.mnemonic | default "" | b64enc }}
  WALLET_PASSWORD: {{ .Values.config.blockchain.walletPassword | default (randAlphaNum 32) | b64enc }}
  CONTRACT_OWNER_KEY: {{ .Values.config.blockchain.contractOwnerKey | default "" | b64enc }}
---
{{- end }}

# License and compliance secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-license-secrets
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: license-secret
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
type: Opaque
data:
  LICENSE_KEY: {{ .Values.config.license.key | default "" | b64enc }}
  COMPLIANCE_TOKEN: {{ .Values.config.license.complianceToken | default "" | b64enc }}
  AUDIT_SECRET: {{ .Values.config.license.auditSecret | default (randAlphaNum 32) | b64enc }}