{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.aws.roleArn }}
    {{- end }}
    {{- if .Values.serviceAccount.gcp.workloadIdentity }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcp.workloadIdentity }}
    {{- end }}
    {{- if .Values.serviceAccount.azure.clientId }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azure.clientId }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}

# AI Processor ServiceAccount (if enabled)
{{- if and .Values.features.ai.enabled .Values.aiProcessor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-ai-processor
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-processor-serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.aiProcessor.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.aiProcessor.serviceAccount.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aiProcessor.serviceAccount.aws.roleArn }}
    {{- end }}
automountServiceAccountToken: {{ .Values.aiProcessor.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}

# Edge Computing ServiceAccount (if enabled)
{{- if and .Values.features.edge.enabled .Values.edgeComputing.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-edge-computing
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge-computing-serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.edgeComputing.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.edgeComputing.serviceAccount.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.edgeComputing.serviceAccount.aws.roleArn }}
    {{- end }}
automountServiceAccountToken: {{ .Values.edgeComputing.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}

# IoT Manager ServiceAccount (if enabled)
{{- if and .Values.features.iot.enabled .Values.iotManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-iot-manager
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: iot-manager-serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.iotManager.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.iotManager.serviceAccount.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.iotManager.serviceAccount.aws.roleArn }}
    {{- end }}
automountServiceAccountToken: {{ .Values.iotManager.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}

# Monitoring ServiceAccount (if enabled)
{{- if and .Values.monitoring.prometheus.enabled .Values.monitoring.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-monitoring
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring-serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.monitoring.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.monitoring.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}

# Backup ServiceAccount (if enabled)
{{- if and .Values.backup.enabled .Values.backup.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-backup
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup-serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.backup.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.backup.serviceAccount.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.backup.serviceAccount.aws.roleArn }}
    {{- end }}
automountServiceAccountToken: {{ .Values.backup.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}

# Development ServiceAccount (if enabled)
{{- if and .Values.development.enabled .Values.development.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventaro-ai.fullname" . }}-development
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "ventaro-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: development-serviceaccount
  annotations:
    {{- include "ventaro-ai.commonAnnotations" . | nindent 4 }}
    {{- with .Values.development.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.development.serviceAccount.automount | default true }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---
{{- end }}